---
# Not enough of a host config setup to warrant a separate file
- name: Install proxmoxer on main host
  ansible.builtin.pip:
    name: proxmoxer

- name: Print the ssh key and store it to a variable
  delegate_to: localhost
  ansible.builtin.shell: "cat {{ machine_ssh_key }}"
  register: ssh_key

- name: Create VM
  community.general.proxmox_kvm:
    node: bigprox
    api_host: "{{host_ip}}"
    api_user: "{{root_user}}"
    api_password: "{{root_password}}"
    vcpus: "{{machine_cpus}}"
    cores: "{{machine_cores}}"
    memory: "{{machine_ram}}"
    name: "{{machine_name}}"
    state: present
    onboot: no
    vmid: "{{machine_id}}"
    sshkeys: "{{ssh_key.stdout}}"
    ipconfig:
      ipconfig0: "gw=192.168.1.1,ip={{machine_ip}}"
    net:
      net0: "model=virtio,bridge=vmbr0,firewall=1"
    scsi:
      scsi0: "local-lvm:{{machine_disk}}"
    scsihw: virtio-scsi-pci
    ide:
      ide0: "local:iso/{{machine_image}},media=cdrom"

- name: Start VM
  community.general.proxmox_kvm:
    node: bigprox
    api_host: "{{host_ip}}"
    api_user: "{{root_user}}"
    api_password: "{{root_password}}"
    name: "{{machine_name}}"
    state: started
