---
- name: Set up Tailscale subnet router
  hosts: "{{node_name}}"
  gather_facts: yes
  become: yes
  become_user: root
  pre_tasks:
    - ansible.builtin.include_vars:
        file: "../../config.json"

  vars_files:
    - ../../vault.yaml

  roles:
    - pm_create_lxc

  
  tasks:
    - name: Run echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf',  'echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf', and 'sudo sysctl -p /etc/sysctl.d/99-tailscale.conf' if '/etc/sysctl.d' directory exists
      ansible.builtin.shell: "echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && sudo sysctl -p /etc/sysctl.d/99-tailscale.conf"
      args:
        executable: /bin/bash
      when: ansible_facts['os_family'] == 'Debian'
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
    - name: Install tailscale using apt
      ansible.builtin.apt:
        name: tailscale
        state: present
      when: ansible_facts['os_family'] == 'Debian'
    
    
