---
# Set up Caddy reverse proxy

- name: Deploy LXC container in Proxmox
  hosts: bigprox
  become: yes
  gather_facts: no
  vars_files:
    - '~/Projects/homelab/secrets.yaml'
  vars:
    host_ip: "{{ proxmox_host_ip }}"
    machine_name: 'caddy'
    machine_password: 'caddy'
    machine_image: "ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
    machine_cores: 1
    machine_cpus: 1
    machine_ram: '512'
    machine_disk: '20'
    onboot: true
    machine_ssh_key: "~/.ssh/proxmox_rsa.pub"
    hookscript: true
    machine_id: '110'
    machine_ip: '192.168.1.4/24'
    api_user: "{{root_user}}"
    api_password: "{{root_password}}"
    install_gui: false
  roles:
    - create_lxc

- name: Update inventory
  hosts: localhost
  roles:
    - add_host
  vars:
    group_name: lxc
    host_name: "caddy"
    host_ip: '192.168.1.4'
    inventory_file: ~/Projects/homelab/inventory.ini
    host_user: "root"

- name: Configure LXC
  hosts: caddy
  vars_files:
    - '~/Projects/homelab/secrets.yaml'
  roles:
    - configure_lxc

- name: Install Docker in the container
  hosts: caddy
  become: yes
  gather_facts: yes
  roles:
    - docker

- name: Deploy Caddy in the container
  hosts: caddy
  roles:
    - caddy_docker
  vars_files:
    - '~/Projects/homelab/secrets.yaml'


# run command: ansible-playbook ansible/playbooks/caddy_build/caddy.yaml --ask-vault-pass -e "host=caddy" 