---
- name: Create an LXC container in Proxmox
  hosts: "{{node_name}}"
  gather_facts: true
  pre_tasks:
    - ansible.builtin.include_vars:
        file: "../../config.json"

  vars_files:
    - ../../vault.yaml

  roles:
    - pm_create_lxc
