---
- name: Check if Docker Compose file exists
  ansible.builtin.stat:
    path: /opt/caddy/docker-compose.yml
  register: result


- name: Stop and remove Caddy container if it exists
  ansible.builtin.docker_compose:
    project_src: /opt/caddy
    state: absent
    remove_images: "all"
    remove_volumes: true
  become: true
  when: result.stat.exists

- name: Restart system
  ansible.builtin.reboot:
    reboot_timeout: 300
  become: true
  when: result.stat.exists

- name: Create caddy directory
  file:
    path: /opt/caddy
    state: directory
  become: true

- name: Copy initial Caddyfile even if it exists
  copy:
    src: Caddyfile
    dest: /opt/caddy/Caddyfile
    force: yes
  become: true

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /opt/caddy/Dockerfile
    force: yes
  become: true

- name: Copy docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/caddy/docker-compose.yml
    force: yes
  become: true

- name: Start Caddy container
  ansible.builtin.docker_compose:
    project_src: /opt/caddy
    state: present
    build: yes
    pull: yes
    nocache: yes
  become: true
