---
- name: Create a LXC Docker container running the official Caddy image 
  hosts: bigprox
  gather_facts: yes
  pre_tasks:
    - ansible.builtin.include_vars:
        file: "./config.json"

  vars_files:
    - ../../../vault.yaml

  roles:
    - pm_create_lxc
    - docker_lxc
  
  tasks:
    - name: Create a Caddyfile in this directory that maps adguard.home to 192.168.1.1 port 8888
      ansible.builtin.copy:
        content: |
          adguard.home {
            reverse_proxy 192.168.1.1:8888
          }
        dest: ./Caddyfile
      delegate_to: "{{machine_ip | regex_replace('/.*', '')}}"
    - name: Create a Caddy container with the Caddyfile mounted
      ansible.builtin.docker_container:
        name: caddy
        image: caddy:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
      delegate_to: "{{machine_ip | regex_replace('/.*', '')}}"
