# services:
#   semaphore:
#     ports:
#       - 3030:3000
#     image: semaphoreui/semaphore:latest
#     environment:
#       SEMAPHORE_DB_DIALECT: bolt
#       SEMAPHORE_ADMIN_PASSWORD: changeme
#       SEMAPHORE_ADMIN_NAME: admin
#       SEMAPHORE_ADMIN_EMAIL: admin@localhost
#       SEMAPHORE_ADMIN: admin

services:
  mysql:
      restart: unless-stopped
      ports:
        - 3306:3306
      image: mysql:8.0
      hostname: mysql
      volumes:
        - semaphore-mysql:/var/lib/mysql
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_DATABASE: semaphore
        MYSQL_USER: semaphore
        MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3030:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql #change to postgres for postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore # change to semaphore?sslmode=disable for postgres
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
    depends_on:
      - mysql #change to postgres for postgres
volumes:
  semaphore-mysql: #swit