---
- name: Test the Ansible command module
  hosts: localhost
  gather_facts: yes

  vars_prompt:
    - name: "machine_type"
      prompt: |
        What is the type of the machine you want to create? 
        Enter one of the following in lowercase:
        - ubuntu
        - debian
        - alpine
      private: no
      default: "ubuntu"

  tasks:
    - name: Run a command on the remote host
      ansible.builtin.command: "python ../image_selector.py -f ../images.ini -s container -i {{machine_type}}"
      register: image_selected
