---
- name: Install Python3 and required packages
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install requests package
  pip:
    name: requests
    state: present
    executable: pip3
