---
- name: Set up an LXC container with Docker running
  hosts: "{{node_name}}"
  gather_facts: yes
  pre_tasks:
    - ansible.builtin.include_vars:
        file: "./config.json"

  vars_files:
    - ../../../vault.yaml

  roles:
    - pm_create_lxc
  
  tasks:
    - name: Verify that the target is online/contactable
      ansible.builtin.ping:
      become: yes
      delegate_to: "{{machine_ip | regex_replace('/.*', '')}}"
    - name: Install Docker
      ansible.builtin.package:
        name: docker.io
        state: present
      become: yes
      delegate_to: "{{machine_ip | regex_replace('/.*', '')}}"
    - name: Enable Docker
      ansible.builtin.service:
        name: docker
        enabled: yes
      become: yes
      delegate_to: "{{machine_ip | regex_replace('/.*', '')}}"
    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
      become: yes
      delegate_to: "{{machine_ip | regex_replace('/.*', '')}}"