---
- name: Install VSCode Server on a fresh ubuntu LXC container
  hosts: "{{node_name}}"
  gather_facts: yes

  vars_files:
    - ../../../secrets.yaml
  
  tasks:
    - name: Verify that the target is online/contactable
      ansible.builtin.ping:
      become: yes
    - name: Install VSCode Server from this url 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64'
      get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64
        dest: /tmp/vscode-server.tar.gz
        mode: 0755
      become: yes
    - name: Unpack the VSCode Server
      unarchive:
        src: /tmp/vscode-server.tar.gz
        dest: /tmp/
        remote_src: yes
      become: yes
    - name: Move the VSCode Server to the correct location
      command: mv /tmp/code /root/code
      become: yes
    - name: Remove the VSCode Server tarball
      file:
        path: /tmp/vscode-server.tar.gz
        state: absent
      become: yes
    - name: Remove the VSCode Server directory 
      file:
        path: /tmp/code
        state: absent
      become: yes
    - name: Create a script called 'codeserverstart.sh'
      copy:
        content: |
          #!/bin/sh
          ./code tunnel
        dest: /usr/local/bin/codeserverstart.sh
        mode: 0755
      become: yes
    - name: Create the VSCode Server systemd service to run './code tunnel' on boot
      copy:
        content: |
          [Unit]
          Description=VSCode Server
          After=network.target

          [Service]
          Type=simple
          User=root
          ExecStart=/usr/local/bin/codeserverstart.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/vscode-server.service
        mode: 0644
      become: yes
    - name: Enable the VSCode Server systemd service
      systemd:
        name: vscode-server
        enabled: yes
      become: yes
    - name: Start the VSCode Server systemd service
      systemd:
        name: vscode-server
        state: started
      become: yes
    